// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Alabastron = "Alabastron",
  Alchemy_Equipment_2 = "Alchemy Equipment_2",
  Ambient_Music___Medieval_2 = "Ambient Music - Medieval 2",
  Blue_Potion = "Blue Potion",
  Building = "Building",
  Corner_Stone_Brick_Wall = "Corner Stone Brick Wall",
  Corner_Stone_Brick_Wall_2 = "Corner Stone Brick Wall_2",
  Drawers_2_3 = "Drawers_2_3",
  Drawers_2_3_5 = "Drawers_2_3_5",
  Drawers_2_3_6 = "Drawers_2_3_6",
  Dreamwhisper_Codex = "Dreamwhisper Codex",
  Elixir = "Elixir",
  Game_Over = "Game Over",
  Green_Potion = "Green Potion",
  Ground = "Ground",
  Invisible_Wall = "Invisible Wall",
  Invisible_Wall_2 = "Invisible Wall_2",
  Invisible_Wall_2_3 = "Invisible Wall_2_3",
  Invisible_Wall_3 = "Invisible Wall_3",
  Lit_Candle_with_Golden_Holder = "Lit Candle with Golden Holder",
  Logs_3 = "Logs 3",
  LongDrawer = "LongDrawer",
  Mines_Wood_Fence1_4M = "Mines Wood Fence1 4M",
  Mines_Wood_Fence1_4M_2 = "Mines Wood Fence1 4M_2",
  Mines_Wood_Fence1_4M_2_3 = "Mines Wood Fence1 4M_2_3",
  Mines_Wood_Fence1_4M_3 = "Mines Wood Fence1 4M_3",
  Pink_Potion = "Pink Potion",
  Plane = "Plane",
  Plane_2 = "Plane_2",
  Plane_2_3 = "Plane_2_3",
  Stone_Brick_Wall = "Stone Brick Wall",
  Stone_Brick_Wall_2 = "Stone Brick Wall_2",
  Stone_Brick_Wall_3 = "Stone Brick Wall_3",
  Stone_Hammer = "Stone Hammer",
  Table = "Table",
  Table_2 = "Table_2",
  Tile_1 = "Tile 1",
  Tweezers = "Tweezers",
} 
