// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Anvil = "Anvil",
  Axe_2 = "Axe 2",
  Barrel_1 = "Barrel 1",
  Barrel_2 = "Barrel 2",
  Barrel_3 = "Barrel 3",
  Barrel_4 = "Barrel 4",
  Books = "Books",
  Bookshelf = "Bookshelf",
  Bookshelf_with_Drawers = "Bookshelf with Drawers",
  Bucket = "Bucket",
  Corner_Stone_Brick_Wall = "Corner Stone Brick Wall",
  Corner_Stone_Brick_Wall_2 = "Corner Stone Brick Wall_2",
  Drawers = "Drawers",
  Drawers_2 = "Drawers_2",
  Drawers_2_3 = "Drawers_2_3",
  Fruit_3 = "Fruit 3",
  Fruit_6 = "Fruit 6",
  Green_Potion = "Green Potion",
  Ground = "Ground",
  Invisible_Wall = "Invisible Wall",
  Iron_Sword = "Iron Sword",
  Logs_2 = "Logs 2",
  Logs_3 = "Logs 3",
  Mines_Cart_Coal = "Mines Cart Coal",
  Mines_Cart_Gold = "Mines Cart Gold",
  Old_Iron_Sword = "Old Iron Sword",
  Pink_Potion = "Pink Potion",
  Pot = "Pot",
  Potion_Cauldron = "Potion Cauldron",
  Red_Magic_Stone = "Red Magic Stone",
  Rustic_Round_Stool = "Rustic Round Stool",
  Salamander_Stove = "Salamander Stove",
  Sit_Spot = "Sit Spot",
  Stone_Brick_Threshold = "Stone Brick Threshold",
  Stone_Brick_Threshold_2 = "Stone Brick Threshold_2",
  Tile_1 = "Tile 1",
  Tweezers = "Tweezers",
  Wooden___Iron_Lamp_Post = "Wooden & Iron Lamp Post",
  Wooden_Axe = "Wooden Axe",
  Wooden_Door_2 = "Wooden Door_2",
  Yellow_Magic_Stone = "Yellow Magic Stone",
  Yellow_Magic_Stone_2 = "Yellow Magic Stone_2",
} 
